import Head from "next/head";
import { dehydrate, QueryClient, useQuery } from "@tanstack/react-query";
import styles from "../styles/Home.module.css";
import { getProducts } from "../lib/products";

export default function Home() {
  const { data } = useQuery({ queryKey: ["products"], queryFn: getProducts });

  if (!data) return <p>No data</p>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data.map((product) => {
          return <div key={product.id}>{product.title}dsffdf</div>;
        })}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery(["products"], getProducts);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
